CREATE DATABASE hotel_alura;

USE hotel_alura;

CREATE USER 'AdminAluraHotel'@'localhost' IDENTIFIED BY 'admin1234';
GRANT ALL PRIVILEGES ON *.* TO 'AdminAluraHotel'@'localhost';


CREATE TABLE CLIENTE(
    ID_CLIENTE INT NOT NULL PRIMARY KEY,
    NOMBRE_CLIENTE VARCHAR(45) NOT NULL,
    APELLIDO_CLIENTE VARCHAR(45) NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    NACIONALIDAD VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(45) NOT NULL,
    FK_RESERVA INT NOT NULL
);

CREATE TABLE RESERVA(
    ID_RESERVA INT NOT NULL PRIMARY KEY,
    FECHA_RESERVA DATE NOT NULL,
    FECHA_ENTRADA DATE NOT NULL,
    FECHA_SALIDA DATE NOT NULL,
    VALOR_TOTAL INT NOT NULL,
    TIPO_PAGO VARCHAR(45) NOT NULL,
    ESTADO VARCHAR(45) NOT NULL
);

DELIMITER $$
CREATE TRIGGER trig_valor_reserva
BEFORE INSERT ON RESERVA
FOR EACH ROW
BEGIN
DECLARE DIAS INT;

SELECT TIMESTAMPDIFF(DAY,NEW.FECHA_ENTRADA,NEW.FECHA_SALIDA) INTO DIAS;

SET NEW.VALOR_TOTAL=DIAS*20;

END $$
DELIMITER $$

DELIMITER $$
CREATE TRIGGER trig_valor_reserva_update
BEFORE UPDATE ON RESERVA
FOR EACH ROW
BEGIN
DECLARE DIAS INT;

SELECT TIMESTAMPDIFF(DAY,NEW.FECHA_ENTRADA,NEW.FECHA_SALIDA) INTO DIAS;

SET NEW.VALOR_TOTAL=DIAS*20;

END $$
DELIMITER $$

ALTER TABLE CLIENTE ADD CONSTRAINT FKCLIENTE1 FOREIGN KEY(FK_RESERVA) REFERENCES RESERVA(ID_RESERVA);

INSERT INTO RESERVA VALUES(1,DATE(NOW()),"2022-12-29","2022-12-31",0,"Tarjet de credito","VERDADERO");

INSERT INTO CLIENTE VALUES(1,"Alejandro","Toledo",'2003-08-14',"Colombiana","34576734",1);


DELIMITER $$
CREATE PROCEDURE guardarHuesped(in APELLIDO VARCHAR(45),in NACIMIENTO DATE,in TELEFONO VARCHAR(30),in NACIONALIDAD VARCHAR(30),in NOMBRE VARCHAR(45))
BEGIN
DECLARE INDICE INT;
DECLARE INDICE2 INT;

START TRANSACTION;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT MAX(ID_CLIENTE)+1 INTO INDICE FROM CLIENTE;
SELECT MAX(ID_RESERVA) INTO INDICE2 FROM RESERVA;

INSERT INTO CLIENTE VALUES(INDICE,NOMBRE,APELLIDO,NACIMIENTO,NACIONALIDAD,TELEFONO,INDICE2);

COMMIT;

END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE guardarReserva(in FECHA_SALIDA DATE,in FECHA_ENTRADA DATE,in TIPO_PAGO VARCHAR(45))
BEGIN
DECLARE INDICE INT;

START TRANSACTION;

SET SESSION TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;

SELECT MAX(ID_RESERVA)+1 INTO INDICE FROM RESERVA;

INSERT INTO RESERVA VALUES(INDICE,DATE(NOW()),FECHA_ENTRADA,FECHA_SALIDA,0,TIPO_PAGO,"VERDADERO");

COMMIT;
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE verReservas()
BEGIN
SELECT ID_RESERVA,FECHA_ENTRADA,FECHA_SALIDA,VALOR_TOTAL,TIPO_PAGO FROM RESERVA WHERE RESERVA.ESTADO="VERDADERO";
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE verHuespedes()
BEGIN
SELECT ID_CLIENTE,NOMBRE_CLIENTE,APELLIDO_CLIENTE,FECHA_NACIMIENTO,NACIONALIDAD,TELEFONO,FK_RESERVA FROM CLIENTE;
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE ActualizarReserva(in nTIPO_PAGO VARCHAR(45),in nFECHA_SALIDA DATE,in nFECHA_ENTRADA DATE ,in ID INT)
BEGIN
UPDATE RESERVA SET TIPO_PAGO=nTIPO_PAGO,FECHA_ENTRADA=nFECHA_ENTRADA,FECHA_SALIDA=nFECHA_SALIDA WHERE ID_RESERVA=ID;
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE EliminarReserva(in ID INT)
BEGIN
UPDATE RESERVA SET ESTADO="FALSO" WHERE ID_RESERVA=ID;
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE EliminarHuesped(in ID INT)
BEGIN
DELETE FROM CLIENTE WHERE ID_CLIENTE=ID;
END $$
DELIMITER $$

DELIMITER $$
CREATE PROCEDURE ActualizarHuesped(in nAPELLIDO VARCHAR(45),in nTELEFONO VARCHAR(45),in ID INT,in nNOMBRE VARCHAR(45))
BEGIN
UPDATE CLIENTE SET NOMBRE_CLIENTE=nNOMBRE,APELLIDO_CLIENTE=nAPELLIDO,TELEFONO=nTELEFONO WHERE ID_CLIENTE=ID;
END $$
DELIMITER $$
